allowBuilds:
  esbuild: true
  sharp: true
  '@scarf/scarf': false
  '@tree-sitter-grammars/tree-sitter-yaml': false
  core-js-pure: false
  tree-sitter-json: false
  tree-sitter: false
  unrs-resolver: false
